"""
This file contains the definitions for the Transformer class as well as its child
classes. 
"""


from abc import abstractmethod
import re
import os
import csv
import logging
from pandas import DataFrame
import pandas as pd
import ijson
from src.config import config

logger = logging.getLogger(__name__)


class Transformer:
    """
        A Transformer processes a JSON file and transforms 
        them into CSV format.

        Attributes
        ----------

        Methods
        ----------
    """
    
    def __init__(self) -> None:
        """
            Instantiates a Transformer object.

            Parameters:
            ----------
            None
        """

    def run(self) -> None:
        """
            Processes raw data files, transforms according to requirements, and
            saves the output as CSV files.
        """
        # We override the direct dataframe approach for memory efficiency (Bonus Task)
        self.process_streaming()

    @abstractmethod
    def process_streaming(self) -> None:
        """
        Processes data using streaming to handle large files.
        """

    @abstractmethod
    def load_data(self) -> DataFrame:
        """
            Loads the raw data file generated by Scraper and generates a DataFrame.
        """

    @abstractmethod
    def transform(self, df: DataFrame) -> DataFrame:
        """
            Consumes the original DataFrame and transforms it to the desired
            output.

            Parameters:
            ----------
            df : DataFrame
                A DataFrame of the raw data

            Returns:
            ----------
            DataFrame
        """

    def save(self, dataframe: DataFrame) -> None:
        """
            Saves the transformed data as CSV file under the data/transformed/
            directory.

            Parameters:
            ----------
            dataframe : DataFrame
                The transformed DataFrame
        """
        os.makedirs(config['TRANSFORMED_DIRECTORY'], exist_ok=True)
        dataframe.to_csv('{}/result.csv'.format(config['TRANSFORMED_DIRECTORY']), index=False)


class BookTransformer(Transformer):
    """
    A BookTransformer is a child of Transformer that transforms the JSON
    data extracted by BookScraper and converts it to CSV.
    """

    def load_data(self) -> DataFrame:
        # Kept for compatibility but process_streaming is preferred for large files
        path = os.path.join(config['RAW_DIRECTORY'], 'data.json')
        return pd.read_json(path)

    def _parse_price(self, price_str: str) -> float:
        if not isinstance(price_str, str):
            return float('nan')
        # remove non-digit, non-dot, non-minus
        cleaned = re.sub(r'[^0-9\.]', '', price_str)
        try:
            return float(cleaned)
        except Exception:
            return float('nan')

    def _rating_to_int(self, rating_str: str) -> int:
        mapping = {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
        return mapping.get(str(rating_str).capitalize(), 0)

    def transform(self, df: DataFrame) -> DataFrame:
        # Kept for compatibility
        df = df.copy()
        # rating to int
        df['_rating_int'] = df['Rating'].apply(self._rating_to_int)
        # price (incl. tax) to float
        df['_price_incl'] = df['Price (incl. tax)'].apply(self._parse_price)

        # filter: at least 4 stars and price < 20
        filtered = df[(df['_rating_int'] >= 4) & (df['_price_incl'] < 20)]

        # drop helper columns and return
        result = filtered.drop(columns=['_rating_int', '_price_incl'])
        return result

    def process_streaming(self) -> None:
        """
        Implementation of the Bonus task: Handle large JSON files using ijson streaming.
        This reads the JSON record by record and writes to CSV immediately if criteria matches.
        """
        input_path = os.path.join(config['RAW_DIRECTORY'], 'data.json')
        output_path = os.path.join(config['TRANSFORMED_DIRECTORY'], 'result.csv')
        
        os.makedirs(config['TRANSFORMED_DIRECTORY'], exist_ok=True)
        
        fields = [
            "UPC", "Product Type", "Price (excl. tax)", "Price (incl. tax)", 
            "Tax", "Availability", "Number of reviews", "Description", 
            "Rating", "Title"
        ]

        logger.info(f"Starting streaming transformation from {input_path}")
        
        count_in = 0
        count_out = 0

        # Note: data.json should be a JSON array of objects
        if not os.path.exists(input_path):
            logger.error(f"Input file not found: {input_path}")
            return

        with open(input_path, 'rb') as f_in, \
             open(output_path, 'w', newline='', encoding='utf-8') as f_out:
            
            writer = csv.DictWriter(f_out, fieldnames=fields)
            writer.writeheader()
            
            # ijson.items streams objects from a list in the JSON file
            parser = ijson.items(f_in, 'item')
            
            for item in parser:
                count_in += 1
                
                # Apply filter logic
                rating_val = self._rating_to_int(item.get('Rating', ''))
                price_val = self._parse_price(item.get('Price (incl. tax)', ''))
                
                # Filter: at least 4 stars AND price < 20
                if rating_val >= 4 and price_val < 20:
                    writer.writerow(item)
                    count_out += 1
                
                if count_in % 100 == 0:
                    logger.debug(f"Processed {count_in} items...")

        logger.info(f"Streaming complete. Processed: {count_in}, Written: {count_out}")
